# Generated by Django 6.0.1 on 2026-01-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionTitle', models.CharField(max_length=50)),
                ('actionDate', models.DateField()),
            ],
        ),
    ]
