# Generated by Django 6.0.1 on 2026-01-18 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='actionTitle',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='actionDate',
            new_name='date',
        ),
    ]
