# Generated by Django 6.0.1 on 2026-01-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_actiontitle_action_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
