# Generated by Django 6.0.1 on 2026-01-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_action_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
